spring.application.name=api-gateway
server.port=9000

services.customer.url=http://localhost:8081
services.movie.url=http://localhost:8082
services.booking.url=http://localhost:8083

app.jwt.secret=fu-cinema-booking-system-secret-key-2026-mss301

management.endpoints.web.exposure.include=health