spring.application.name=api-gateway
server.port=9000

services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
management.endpoints.web.exposure.include=health
