spring.application.name=booking-service
server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_booking?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

movie.service.url=http://localhost:8082
